### PR TITLE
Update to mimetic 0.9.8

### PR DESCRIPTION
**Pull request by BadPirate**
Dropped in the new library, and update the PodSpec, I won't have the ability to update the pod spec trunk, so hoping you can take care of that @OliverLetterer -- Much obliged!

### CODE REVIEW

**Comment by OliverLetterer** [comment]
mimetic (0.9.8) is now live on trunk. Thanks for the pull request 🎉🎊✨

**Comment by BadPirate** [comment]
Any chance you could run pod spec update?

**Comment by OliverLetterer** [comment]
What do you mean? This repo does not contain a Podfile.

**Comment by BadPirate** [comment]
Podspec actually. 

—

**Comment by OliverLetterer** [comment]
I still don't understand. Sorry.

**Comment by BadPirate** [comment]
Hmm. Pod search mimetic returns 0.9.7, but pod trunk info mimetic shows 0.9.8. Looks like you pushed the changes, not sure why it still shows old version in search. :/

—

**Comment by OliverLetterer** [comment]
Maybe you have multiple versions in different repositories?

**Pull request merged**
